// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using APIKeyAuthConfig within kubernetes types, where deepcopy-gen is used.
func (in *APIKeyAuthConfig) DeepCopyInto(out *APIKeyAuthConfig) {
	p := proto.Clone(in).(*APIKeyAuthConfig)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyAuthConfig. Required by controller-gen.
func (in *APIKeyAuthConfig) DeepCopy() *APIKeyAuthConfig {
	if in == nil {
		return nil
	}
	out := new(APIKeyAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyAuthConfig. Required by controller-gen.
func (in *APIKeyAuthConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using APIKeyAuthConfig_AuthServer within kubernetes types, where deepcopy-gen is used.
func (in *APIKeyAuthConfig_AuthServer) DeepCopyInto(out *APIKeyAuthConfig_AuthServer) {
	p := proto.Clone(in).(*APIKeyAuthConfig_AuthServer)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyAuthConfig_AuthServer. Required by controller-gen.
func (in *APIKeyAuthConfig_AuthServer) DeepCopy() *APIKeyAuthConfig_AuthServer {
	if in == nil {
		return nil
	}
	out := new(APIKeyAuthConfig_AuthServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyAuthConfig_AuthServer. Required by controller-gen.
func (in *APIKeyAuthConfig_AuthServer) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UsageStatsConfig within kubernetes types, where deepcopy-gen is used.
func (in *UsageStatsConfig) DeepCopyInto(out *UsageStatsConfig) {
	p := proto.Clone(in).(*UsageStatsConfig)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageStatsConfig. Required by controller-gen.
func (in *UsageStatsConfig) DeepCopy() *UsageStatsConfig {
	if in == nil {
		return nil
	}
	out := new(UsageStatsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UsageStatsConfig. Required by controller-gen.
func (in *UsageStatsConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UsageStatsConfig_StatsServer within kubernetes types, where deepcopy-gen is used.
func (in *UsageStatsConfig_StatsServer) DeepCopyInto(out *UsageStatsConfig_StatsServer) {
	p := proto.Clone(in).(*UsageStatsConfig_StatsServer)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageStatsConfig_StatsServer. Required by controller-gen.
func (in *UsageStatsConfig_StatsServer) DeepCopy() *UsageStatsConfig_StatsServer {
	if in == nil {
		return nil
	}
	out := new(UsageStatsConfig_StatsServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UsageStatsConfig_StatsServer. Required by controller-gen.
func (in *UsageStatsConfig_StatsServer) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OpenAIRequestMarshallerConfig within kubernetes types, where deepcopy-gen is used.
func (in *OpenAIRequestMarshallerConfig) DeepCopyInto(out *OpenAIRequestMarshallerConfig) {
	p := proto.Clone(in).(*OpenAIRequestMarshallerConfig)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIRequestMarshallerConfig. Required by controller-gen.
func (in *OpenAIRequestMarshallerConfig) DeepCopy() *OpenAIRequestMarshallerConfig {
	if in == nil {
		return nil
	}
	out := new(OpenAIRequestMarshallerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIRequestMarshallerConfig. Required by controller-gen.
func (in *OpenAIRequestMarshallerConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OpenAIResponseUnmarshallerConfig within kubernetes types, where deepcopy-gen is used.
func (in *OpenAIResponseUnmarshallerConfig) DeepCopyInto(out *OpenAIResponseUnmarshallerConfig) {
	p := proto.Clone(in).(*OpenAIResponseUnmarshallerConfig)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIResponseUnmarshallerConfig. Required by controller-gen.
func (in *OpenAIResponseUnmarshallerConfig) DeepCopy() *OpenAIResponseUnmarshallerConfig {
	if in == nil {
		return nil
	}
	out := new(OpenAIResponseUnmarshallerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIResponseUnmarshallerConfig. Required by controller-gen.
func (in *OpenAIResponseUnmarshallerConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OpenAIModelNameRewriteConfig within kubernetes types, where deepcopy-gen is used.
func (in *OpenAIModelNameRewriteConfig) DeepCopyInto(out *OpenAIModelNameRewriteConfig) {
	p := proto.Clone(in).(*OpenAIModelNameRewriteConfig)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIModelNameRewriteConfig. Required by controller-gen.
func (in *OpenAIModelNameRewriteConfig) DeepCopy() *OpenAIModelNameRewriteConfig {
	if in == nil {
		return nil
	}
	out := new(OpenAIModelNameRewriteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIModelNameRewriteConfig. Required by controller-gen.
func (in *OpenAIModelNameRewriteConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
