// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using APIKeyAuthRequest within kubernetes types, where deepcopy-gen is used.
func (in *APIKeyAuthRequest) DeepCopyInto(out *APIKeyAuthRequest) {
	p := proto.Clone(in).(*APIKeyAuthRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyAuthRequest. Required by controller-gen.
func (in *APIKeyAuthRequest) DeepCopy() *APIKeyAuthRequest {
	if in == nil {
		return nil
	}
	out := new(APIKeyAuthRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyAuthRequest. Required by controller-gen.
func (in *APIKeyAuthRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using APIKeyAuthResponse within kubernetes types, where deepcopy-gen is used.
func (in *APIKeyAuthResponse) DeepCopyInto(out *APIKeyAuthResponse) {
	p := proto.Clone(in).(*APIKeyAuthResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyAuthResponse. Required by controller-gen.
func (in *APIKeyAuthResponse) DeepCopy() *APIKeyAuthResponse {
	if in == nil {
		return nil
	}
	out := new(APIKeyAuthResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyAuthResponse. Required by controller-gen.
func (in *APIKeyAuthResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
