// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using UsageReportRequest within kubernetes types, where deepcopy-gen is used.
func (in *UsageReportRequest) DeepCopyInto(out *UsageReportRequest) {
	p := proto.Clone(in).(*UsageReportRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageReportRequest. Required by controller-gen.
func (in *UsageReportRequest) DeepCopy() *UsageReportRequest {
	if in == nil {
		return nil
	}
	out := new(UsageReportRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UsageReportRequest. Required by controller-gen.
func (in *UsageReportRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UsageReportRequest_Usage within kubernetes types, where deepcopy-gen is used.
func (in *UsageReportRequest_Usage) DeepCopyInto(out *UsageReportRequest_Usage) {
	p := proto.Clone(in).(*UsageReportRequest_Usage)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageReportRequest_Usage. Required by controller-gen.
func (in *UsageReportRequest_Usage) DeepCopy() *UsageReportRequest_Usage {
	if in == nil {
		return nil
	}
	out := new(UsageReportRequest_Usage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UsageReportRequest_Usage. Required by controller-gen.
func (in *UsageReportRequest_Usage) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UsageReportResponse within kubernetes types, where deepcopy-gen is used.
func (in *UsageReportResponse) DeepCopyInto(out *UsageReportResponse) {
	p := proto.Clone(in).(*UsageReportResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageReportResponse. Required by controller-gen.
func (in *UsageReportResponse) DeepCopy() *UsageReportResponse {
	if in == nil {
		return nil
	}
	out := new(UsageReportResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UsageReportResponse. Required by controller-gen.
func (in *UsageReportResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
