version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - anypb
  - apikey
  - apimachinery
  - Causef
  - clientgoscheme
  - clusterfilters
  - copyloopvar
  - dupl
  - durationcheck
  - errcheck
  - errname
  - evanphx
  - exhaustive
  - forcetypeassert
  - genclient
  - ginkgolinter
  - goconst
  - gocyclo
  - gofmt
  - goimports
  - goopenai
  - gosimple
  - govet
  - healthz
  - ineffassign
  - jsonpatch
  - knoway
  - knowaydevv1alpha1
  - kubebuilder
  - listenerfilters
  - lll
  - llmbackends
  - metav1
  - metricsserver
  - misspell
  - nakedret
  - nilfunc
  - nolint
  - nolintlint
  - nosniff
  - nosprintfhostport
  - prealloc
  - predeclared
  - printcolumn
  - protoutils
  - readyz
  - reassign
  - registryfilters
  - revive
  - samber
  - sashabaranov
  - staticcheck
  - stretchr
  - subresource
  - typecheck
  - unconvert
  - unmarshalled
  - Unmarshaller
  - unparam
  - unused
  - usestdlibvars
  - utilruntime
  - whitespace
  - wsl
ignoreWords: []
import: []
