version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - anypb
  - apikey
  - apimachinery
  - bootkit
  - bufconn
  - bufnet
  - Causef
  - clientgoscheme
  - clusterfilters
  - containedctx
  - contextcheck
  - copyloopvar
  - cyclop
  - depguard
  - dupl
  - durationcheck
  - Equalf
  - err113
  - errcheck
  - errchkjson
  - errname
  - evanphx
  - execinquery
  - exhaustive
  - exhaustruct
  - exportloopref
  - forcetypeassert
  - funlen
  - gci
  - genclient
  - ginkgolinter
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - godox
  - gofmt
  - gofumpt
  - goimports
  - gomnd
  - goopenai
  - gosec
  - gosimple
  - govet
  - healthz
  - ineffassign
  - ireturn
  - jsonpatch
  - knoway
  - knowaydevv1alpha1
  - kubebuilder
  - listenerfilters
  - lll
  - llmbackends
  - maintidx
  - metav1
  - metricsserver
  - misspell
  - nakedret
  - nestif
  - nilfunc
  - nilnil
  - nlreturn
  - nolint
  - nolintlint
  - nosniff
  - nosprintfhostport
  - paralleltest
  - perfsprint
  - prealloc
  - predeclared
  - printcolumn
  - protoutils
  - readyz
  - reassign
  - registryfilters
  - revive
  - samber
  - sashabaranov
  - staticcheck
  - stretchr
  - stylecheck
  - subresource
  - tagalign
  - tagliatelle
  - testpackage
  - typecheck
  - unconvert
  - unmarshalled
  - Unmarshaller
  - unparam
  - unused
  - usestdlibvars
  - utilruntime
  - varnamelen
  - whitespace
  - wrapcheck
  - wsl
ignoreWords: []
import: []
