apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.name }}
    namespace: {{ .Release.Namespace }}
