apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.fullNameOverride | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullNameOverride | default .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.fullNameOverride | default .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.fullNameOverride | default .Release.Name }}
    namespace: {{ .Release.Namespace }}
