apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullNameOverride | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullNameOverride | default .Release.Name }}
data:
  config.yaml: |-
    debug: {{.Values.debug }}
    gateway:
      auth_server:
        url: {{.Values.config.auth_server_url }}
      stats_server:
        url: {{.Values.config.stats_server_url }}
