apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullNameOverride | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullNameOverride | default .Release.Name }}
data:
  config.yaml: |-
    debug: {{.Values.debug }}
    staticListeners:
      chat:
        name: openai-chat
        filters:
          - name: api-key-auth
            config:
              '@type': type.googleapis.com/knoway.filters.v1alpha1.APIKeyAuthConfig
              authServer:
                url: {{ .Values.config.auth_server.url }}
                timeout: {{ .Values.config.auth_server.timeout }}
          - config:
              '@type': type.googleapis.com/knoway.filters.v1alpha1.UsageStatsConfig
              statsServer:
                url: {{ .Values.config.stats_server.url }}
                timeout: {{ .Values.config.stats_server.timeout }}
          {{- if .Values.config.rate_limit.enable }}
          - config:
              '@type': type.googleapis.com/knoway.filters.v1alpha1.RateLimitConfig
              policies: {{- toYaml .Values.config.rate_limit.policies | nindent 16 }}
          {{- end }}
        accessLog: {{- toYaml .Values.config.log.access_log | nindent 10 }}
      image:
        name: openai-image
        filters:
          - name: api-key-auth
            config:
              '@type': type.googleapis.com/knoway.filters.v1alpha1.APIKeyAuthConfig
              authServer:
                url: {{ .Values.config.auth_server.url }}
                timeout: {{ .Values.config.auth_server.timeout }}
          - config:
              '@type': type.googleapis.com/knoway.filters.v1alpha1.UsageStatsConfig
              statsServer:
                url: {{ .Values.config.stats_server.url }}
                timeout: {{ .Values.config.stats_server.timeout }}
          {{- if .Values.config.rate_limit.enable }}
          - config:
              '@type': type.googleapis.com/knoway.filters.v1alpha1.RateLimitConfig
              policies: {{- toYaml .Values.config.rate_limit.policies | nindent 16 }}
          {{- end }}
        accessLog: {{- toYaml .Values.config.log.access_log | nindent 10 }}
