apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullNameOverride | default .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullNameOverride | default .Release.Name }}-gateway
spec:
  replicas: {{ include "replicas" . }}
  selector:
    matchLabels:
      app: {{ .Values.fullNameOverride | default .Release.Name }}-gateway
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.fullNameOverride | default .Release.Name }}-gateway
    spec:
      {{- include "common.images.pullSecrets" . | indent 6 }}
      {{- if and (.Values.global.nodeSelector) (not .Values.gateway.nodeSelector) }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.gateway.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.gateway.nodeSelector | indent 8 }}
    {{- end }}
    {{- if and (.Values.global.affinity) (not .Values.gateway.affinity) }}
      affinity:
{{ toYaml .Values.global.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.gateway.affinity }}
      affinity:
{{ toYaml .Values.gateway.affinity | indent 8 }}
    {{- end }}
    {{- if and (.Values.global.tolerations) (not .Values.gateway.tolerations) }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.gateway.tolerations }}
      tolerations:
{{ toYaml .Values.gateway.tolerations | indent 8 }}
    {{- end }}
      dnsPolicy: ClusterFirst
      containers:
        - name: proxy
          image: {{ template "knoway.gateway.image" . }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- if include "common.images.resources" . }}
          resources:
          {{- include "common.images.resources" . | indent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - readOnly: true
              mountPath: /app/config
              name: config
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 15
      serviceAccountName: {{ .Values.fullNameOverride | default .Release.Name }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.fullNameOverride | default .Release.Name }}
