{{ if .Values.global.use_hpa }}
{{ if .Capabilities.APIVersions.Has "autoscaling/v2/HorizontalPodAutoscaler" -}}
apiVersion: autoscaling/v2
{{ else }}
apiVersion: autoscaling/v1
{{ end }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ .Values.fullNameOverride | default .Release.Name }}-gateway
  name: {{ .Values.fullNameOverride | default .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  maxReplicas: 2
  {{ if .Capabilities.APIVersions.Has "autoscaling/v2/HorizontalPodAutoscaler" -}}
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  {{ else }}
  targetCPUUtilizationPercentage: 80
  {{ end }}
  minReplicas: {{ include "hpa.min_replicas" . }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.fullNameOverride | default .Release.Name }}-gateway
{{ end }}
