// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using RouteFilter within kubernetes types, where deepcopy-gen is used.
func (in *RouteFilter) DeepCopyInto(out *RouteFilter) {
	p := proto.Clone(in).(*RouteFilter)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteFilter. Required by controller-gen.
func (in *RouteFilter) DeepCopy() *RouteFilter {
	if in == nil {
		return nil
	}
	out := new(RouteFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RouteFilter. Required by controller-gen.
func (in *RouteFilter) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using StringMatch within kubernetes types, where deepcopy-gen is used.
func (in *StringMatch) DeepCopyInto(out *StringMatch) {
	p := proto.Clone(in).(*StringMatch)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringMatch. Required by controller-gen.
func (in *StringMatch) DeepCopy() *StringMatch {
	if in == nil {
		return nil
	}
	out := new(StringMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new StringMatch. Required by controller-gen.
func (in *StringMatch) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Match within kubernetes types, where deepcopy-gen is used.
func (in *Match) DeepCopyInto(out *Match) {
	p := proto.Clone(in).(*Match)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Match. Required by controller-gen.
func (in *Match) DeepCopy() *Match {
	if in == nil {
		return nil
	}
	out := new(Match)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Match. Required by controller-gen.
func (in *Match) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Route within kubernetes types, where deepcopy-gen is used.
func (in *Route) DeepCopyInto(out *Route) {
	p := proto.Clone(in).(*Route)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route. Required by controller-gen.
func (in *Route) DeepCopy() *Route {
	if in == nil {
		return nil
	}
	out := new(Route)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Route. Required by controller-gen.
func (in *Route) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
