---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - knoway.dev.knoway.dev
  resources:
  - llmbackends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - knoway.dev.knoway.dev
  resources:
  - llmbackends/finalizers
  verbs:
  - update
- apiGroups:
  - knoway.dev.knoway.dev
  resources:
  - llmbackends/status
  verbs:
  - get
  - patch
  - update
