---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - llm.knoway.dev
  resources:
  - imagegenerationbackends
  - llmbackends
  - modelroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llm.knoway.dev
  resources:
  - imagegenerationbackends/finalizers
  - llmbackends/finalizers
  - modelroutes/finalizers
  verbs:
  - update
- apiGroups:
  - llm.knoway.dev
  resources:
  - imagegenerationbackends/status
  - llmbackends/status
  - modelroutes/status
  verbs:
  - get
  - patch
  - update
