listeners:
  filters:
    - name: "api-key-auth"
      config:
         type: "type.googleapis.com/v1alpha2.APIKeyAuthConfig"  # 这里假设你需要指定类型
         AuthServer: null
clusters:
  - name: "model1"
    filters:
      - name: "usage-stats"
        config:
          type: "type.googleapis.com/v1alpha2.UsageStatsConfig"  # 这里假设你需要指定类型
          # todo
