apiVersion: knoway.dev.knoway.dev/v1alpha1
kind: LLMBackend
metadata:
  labels:
    app.kubernetes.io/name: knoway
    app.kubernetes.io/managed-by: kustomize
  name: llmbackend-sample
spec:
#  # 优先级 address > selector
#  endpoint:
#    address: www.openai.com
#    selector:
#      app: openai-gpt-4o
#  type: public # public | private | ...
  provider: openai
  modelName: gpt-4o
  SecretRef: gpt-4o-openai-apikey
  filters:
    - name: "usage-stats"
      type: "type.googleapis.com/knoway.filters.v1alpha1.UsageStatsConfig"
      usageStatsConfig:
        stats_server:
          url: "0.0.0.0:9090"
    - name: "image-filter"
      # 记录 filter 类型或者所属
      labels:
        xxx.exmaple.com/category: image
    - name: "base64-filter"
#      config: # todo
# future:
#  maxToken: 242444
#  capability:
#    steam: true
#    image: true
#    base64: true
#status:
#  conditions:
#    - config-validator
#    - endpoint-check
#    - secret-check
