apiVersion: llm.knoway.dev/v1alpha1
kind: ModelRoute
metadata:
  labels:
    app.kubernetes.io/name: knoway
    app.kubernetes.io/managed-by: kustomize
  name: modelroute-example
spec:
  modelName: public/sample:auto
  route:
    loadBalancePolicy: WeightedRoundRobin
    targets:
      - destination:
          backend: llmbackend-sample
          namespace: public
