apiVersion: llm.knoway.dev/v1alpha1
kind: LLMBackend
metadata:
  labels:
    app.kubernetes.io/name: knoway
    app.kubernetes.io/managed-by: kustomize
  name: llmbackend-sample
spec:
  #  type: public # public | private | ...
  provider: openai
  name: gpt-3.5-turbo
  modelName: openai/gpt-3.5-turbo
  upstream:
    baseURL: "https://openrouter.ai/api/v1/chat/completions"
    headers:
      - key: "Authorization"
        value: "Bearer sk-or-v1-xxxxxxxxxx"
    timeout: 300 # ms
    defaultParams:
      openai:
        temperature: "0.5"
    overrideParams:
      openai:
        # upstream model
        model: "openai/gpt-3.5-turbo"
        max_tokens: 100
  filters:
    - custom:
        pluginName: "examplePlugin"
        pluginVersion: "1.0.0"
# future:
#  maxToken: 242444
#  capability:
#    steam: true
#    image: true
#    base64: true
#status:
#  conditions:
#    - config-validator
#    - endpoint-check
#    - secret-check
