apiVersion: llm.knoway.dev/v1alpha1
kind: ModelRoute
metadata:
  labels:
    app.kubernetes.io/name: knoway
    app.kubernetes.io/managed-by: kustomize
  name: modelroute-example
spec:
  modelName: deepseek-r1
  rateLimit:
    - match:
        value:
          prefix: sk-prj-123
      limit: 100
      basedOn: APIKey
      duration: 1m
    - match:
        value:
          exact: u-4587
      limit: 100
      basedOn: APIKey
      duration: 1m
    - limit: 1
      basedOn: UserID
      duration: 1m
  route:
    loadBalancePolicy: "WeightedRoundRobin"
    targets:
      - destination:
          backend: deepseek-r1
          namespace: public
          weight: 1
      - destination:
          backend: deepseek-r1-4090
          namespace: public
          weight: 2
