// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using LLMBackendSpec within kubernetes types, where deepcopy-gen is used.
func (in *LLMBackendSpec) DeepCopyInto(out *LLMBackendSpec) {
	p := proto.Clone(in).(*LLMBackendSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendSpec. Required by controller-gen.
func (in *LLMBackendSpec) DeepCopy() *LLMBackendSpec {
	if in == nil {
		return nil
	}
	out := new(LLMBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendSpec. Required by controller-gen.
func (in *LLMBackendSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UsageStatsConfig within kubernetes types, where deepcopy-gen is used.
func (in *UsageStatsConfig) DeepCopyInto(out *UsageStatsConfig) {
	p := proto.Clone(in).(*UsageStatsConfig)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageStatsConfig. Required by controller-gen.
func (in *UsageStatsConfig) DeepCopy() *UsageStatsConfig {
	if in == nil {
		return nil
	}
	out := new(UsageStatsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UsageStatsConfig. Required by controller-gen.
func (in *UsageStatsConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OpenAIModelNameRewriteConfig within kubernetes types, where deepcopy-gen is used.
func (in *OpenAIModelNameRewriteConfig) DeepCopyInto(out *OpenAIModelNameRewriteConfig) {
	p := proto.Clone(in).(*OpenAIModelNameRewriteConfig)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIModelNameRewriteConfig. Required by controller-gen.
func (in *OpenAIModelNameRewriteConfig) DeepCopy() *OpenAIModelNameRewriteConfig {
	if in == nil {
		return nil
	}
	out := new(OpenAIModelNameRewriteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIModelNameRewriteConfig. Required by controller-gen.
func (in *OpenAIModelNameRewriteConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using LLMBackendFilter within kubernetes types, where deepcopy-gen is used.
func (in *LLMBackendFilter) DeepCopyInto(out *LLMBackendFilter) {
	p := proto.Clone(in).(*LLMBackendFilter)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendFilter. Required by controller-gen.
func (in *LLMBackendFilter) DeepCopy() *LLMBackendFilter {
	if in == nil {
		return nil
	}
	out := new(LLMBackendFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendFilter. Required by controller-gen.
func (in *LLMBackendFilter) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using LLMBackendStatus within kubernetes types, where deepcopy-gen is used.
func (in *LLMBackendStatus) DeepCopyInto(out *LLMBackendStatus) {
	p := proto.Clone(in).(*LLMBackendStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendStatus. Required by controller-gen.
func (in *LLMBackendStatus) DeepCopy() *LLMBackendStatus {
	if in == nil {
		return nil
	}
	out := new(LLMBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendStatus. Required by controller-gen.
func (in *LLMBackendStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
