// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: v1alpha1/llmbakcend.proto

package v1alpha1

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LLMBackendSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelName string              `protobuf:"bytes,1,opt,name=modelName,proto3" json:"modelName,omitempty"`
	Provider  string              `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	SecretRef string              `protobuf:"bytes,3,opt,name=secretRef,proto3" json:"secretRef,omitempty"`
	Filters   []*LLMBackendFilter `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *LLMBackendSpec) Reset() {
	*x = LLMBackendSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_llmbakcend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMBackendSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMBackendSpec) ProtoMessage() {}

func (x *LLMBackendSpec) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_llmbakcend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMBackendSpec.ProtoReflect.Descriptor instead.
func (*LLMBackendSpec) Descriptor() ([]byte, []int) {
	return file_v1alpha1_llmbakcend_proto_rawDescGZIP(), []int{0}
}

func (x *LLMBackendSpec) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *LLMBackendSpec) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMBackendSpec) GetSecretRef() string {
	if x != nil {
		return x.SecretRef
	}
	return ""
}

func (x *LLMBackendSpec) GetFilters() []*LLMBackendFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type UsageStatsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *UsageStatsConfig) Reset() {
	*x = UsageStatsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_llmbakcend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsageStatsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageStatsConfig) ProtoMessage() {}

func (x *UsageStatsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_llmbakcend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageStatsConfig.ProtoReflect.Descriptor instead.
func (*UsageStatsConfig) Descriptor() ([]byte, []int) {
	return file_v1alpha1_llmbakcend_proto_rawDescGZIP(), []int{1}
}

func (x *UsageStatsConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type OpenAIModelNameRewriteConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelName string `protobuf:"bytes,2,opt,name=modelName,proto3" json:"modelName,omitempty"`
}

func (x *OpenAIModelNameRewriteConfig) Reset() {
	*x = OpenAIModelNameRewriteConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_llmbakcend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenAIModelNameRewriteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAIModelNameRewriteConfig) ProtoMessage() {}

func (x *OpenAIModelNameRewriteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_llmbakcend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAIModelNameRewriteConfig.ProtoReflect.Descriptor instead.
func (*OpenAIModelNameRewriteConfig) Descriptor() ([]byte, []int) {
	return file_v1alpha1_llmbakcend_proto_rawDescGZIP(), []int{2}
}

func (x *OpenAIModelNameRewriteConfig) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type LLMBackendFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type             string                        `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UsageStatsConfig *UsageStatsConfig             `protobuf:"bytes,3,opt,name=usageStatsConfig,proto3" json:"usageStatsConfig,omitempty"`
	RewriteConfig    *OpenAIModelNameRewriteConfig `protobuf:"bytes,4,opt,name=rewriteConfig,proto3" json:"rewriteConfig,omitempty"`
}

func (x *LLMBackendFilter) Reset() {
	*x = LLMBackendFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_llmbakcend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMBackendFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMBackendFilter) ProtoMessage() {}

func (x *LLMBackendFilter) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_llmbakcend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMBackendFilter.ProtoReflect.Descriptor instead.
func (*LLMBackendFilter) Descriptor() ([]byte, []int) {
	return file_v1alpha1_llmbakcend_proto_rawDescGZIP(), []int{3}
}

func (x *LLMBackendFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LLMBackendFilter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LLMBackendFilter) GetUsageStatsConfig() *UsageStatsConfig {
	if x != nil {
		return x.UsageStatsConfig
	}
	return nil
}

func (x *LLMBackendFilter) GetRewriteConfig() *OpenAIModelNameRewriteConfig {
	if x != nil {
		return x.RewriteConfig
	}
	return nil
}

type LLMBackendStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phase string `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
}

func (x *LLMBackendStatus) Reset() {
	*x = LLMBackendStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_llmbakcend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMBackendStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMBackendStatus) ProtoMessage() {}

func (x *LLMBackendStatus) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_llmbakcend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMBackendStatus.ProtoReflect.Descriptor instead.
func (*LLMBackendStatus) Descriptor() ([]byte, []int) {
	return file_v1alpha1_llmbakcend_proto_rawDescGZIP(), []int{4}
}

func (x *LLMBackendStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

var File_v1alpha1_llmbakcend_proto protoreflect.FileDescriptor

var file_v1alpha1_llmbakcend_proto_rawDesc = []byte{
	0x0a, 0x19, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6c, 0x6c, 0x6d, 0x62, 0x61,
	0x6b, 0x63, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01, 0x0a, 0x0e, 0x4c, 0x4c,
	0x4d, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1c, 0x0a, 0x09,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x52, 0x65, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x52, 0x65, 0x66, 0x12, 0x2b, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4c, 0x4c, 0x4d, 0x42, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x73, 0x22, 0x2c, 0x0a, 0x10, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x3c, 0x0a, 0x1c, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x49, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x77, 0x72, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xbe, 0x01,
	0x0a, 0x10, 0x4c, 0x4c, 0x4d, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x10, 0x75, 0x73,
	0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x10, 0x75, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x43, 0x0a, 0x0d, 0x72, 0x65, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x49, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x77, 0x72, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x0d, 0x72, 0x65, 0x77, 0x72, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x28,
	0x0a, 0x10, 0x4c, 0x4c, 0x4d, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x6b, 0x6e, 0x6f, 0x77,
	0x61, 0x79, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1alpha1_llmbakcend_proto_rawDescOnce sync.Once
	file_v1alpha1_llmbakcend_proto_rawDescData = file_v1alpha1_llmbakcend_proto_rawDesc
)

func file_v1alpha1_llmbakcend_proto_rawDescGZIP() []byte {
	file_v1alpha1_llmbakcend_proto_rawDescOnce.Do(func() {
		file_v1alpha1_llmbakcend_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1alpha1_llmbakcend_proto_rawDescData)
	})
	return file_v1alpha1_llmbakcend_proto_rawDescData
}

var file_v1alpha1_llmbakcend_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1alpha1_llmbakcend_proto_goTypes = []interface{}{
	(*LLMBackendSpec)(nil),               // 0: LLMBackendSpec
	(*UsageStatsConfig)(nil),             // 1: UsageStatsConfig
	(*OpenAIModelNameRewriteConfig)(nil), // 2: OpenAIModelNameRewriteConfig
	(*LLMBackendFilter)(nil),             // 3: LLMBackendFilter
	(*LLMBackendStatus)(nil),             // 4: LLMBackendStatus
}
var file_v1alpha1_llmbakcend_proto_depIdxs = []int32{
	3, // 0: LLMBackendSpec.filters:type_name -> LLMBackendFilter
	1, // 1: LLMBackendFilter.usageStatsConfig:type_name -> UsageStatsConfig
	2, // 2: LLMBackendFilter.rewriteConfig:type_name -> OpenAIModelNameRewriteConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1alpha1_llmbakcend_proto_init() }
func file_v1alpha1_llmbakcend_proto_init() {
	if File_v1alpha1_llmbakcend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1alpha1_llmbakcend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMBackendSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_llmbakcend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsageStatsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_llmbakcend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenAIModelNameRewriteConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_llmbakcend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMBackendFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_llmbakcend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMBackendStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1alpha1_llmbakcend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1alpha1_llmbakcend_proto_goTypes,
		DependencyIndexes: file_v1alpha1_llmbakcend_proto_depIdxs,
		MessageInfos:      file_v1alpha1_llmbakcend_proto_msgTypes,
	}.Build()
	File_v1alpha1_llmbakcend_proto = out.File
	file_v1alpha1_llmbakcend_proto_rawDesc = nil
	file_v1alpha1_llmbakcend_proto_goTypes = nil
	file_v1alpha1_llmbakcend_proto_depIdxs = nil
}
