debug: true
controller:
  secure_metrics: false
  enable_http2: false
kubeConfig: ""
staticListeners:
  - '@type': type.googleapis.com/knoway.listeners.v1alpha1.ChatCompletionListener
    name: openai-chat
    # filters:
    #   - name: api-key-auth
    #     config:
    #       '@type': type.googleapis.com/knoway.filters.v1alpha1.APIKeyAuthConfig
    #       authServer:
    #         url: console.d.run:443
    #         timeout: 0s
    #   - config:
    #       '@type': type.googleapis.com/knoway.filters.v1alpha1.UsageStatsConfig
    #       statsServer:
    #         url: console.d.run:443
    #         timeout: 0s
    #   - config:
    #       '@type': type.googleapis.com/knoway.filters.v1alpha1.RateLimitConfig
    #       policies:
    #         - limit: 0
    #           based_on: USER_ID
    #           duration: 30s
    filters:
      - name: api-key-auth
        config:
          '@type': type.googleapis.com/knoway.filters.v1alpha1.APIKeyAuthConfig
          authServer:
            url: console.d.run:443
            timeout: 0s
      - config:
          '@type': type.googleapis.com/knoway.filters.v1alpha1.UsageStatsConfig
          statsServer:
            url: console.d.run:443
            timeout: 0s
      - config:
          '@type': type.googleapis.com/knoway.filters.v1alpha1.RateLimitConfig
          policies:
            - basedOn: USER_ID
              duration: 30s
    accessLog:
      enable: true
  - '@type': type.googleapis.com/knoway.listeners.v1alpha1.ImageListener
    name: openai-image
    # filters:
    #   - name: api-key-auth
    #     config:
    #       '@type': type.googleapis.com/knoway.filters.v1alpha1.APIKeyAuthConfig
    #       authServer:
    #         url: console.d.run:443
    #         timeout: 0s
    #   - config:
    #       '@type': type.googleapis.com/knoway.filters.v1alpha1.UsageStatsConfig
    #       statsServer:
    #         url: console.d.run:443
    #         timeout: 0s
    #   - config:
    #       '@type': type.googleapis.com/knoway.filters.v1alpha1.RateLimitConfig
    #       policies:
    #         - limit: 0
    #           based_on: USER_ID
    #           duration: 30s
    filters:
      - name: api-key-auth
        config:
          '@type': type.googleapis.com/knoway.filters.v1alpha1.APIKeyAuthConfig
          authServer:
            url: console.d.run:443
            timeout: 0s
      - config:
          '@type': type.googleapis.com/knoway.filters.v1alpha1.UsageStatsConfig
          statsServer:
            url: console.d.run:443
            timeout: 0s
      - config:
          '@type': type.googleapis.com/knoway.filters.v1alpha1.RateLimitConfig
          policies:
            - basedOn: USER_ID
              duration: 30s
    accessLog:
      enable: true
