debug: true
controller:
  secure_metrics: false
  enable_http2: false
kubeConfig: ""
staticListeners:
  chat:
    name: openai-chat
    filters:
      - name: api-key-auth
        config:
          '@type': type.googleapis.com/knoway.filters.v1alpha1.APIKeyAuthConfig
          authServer:
            url: console.d.run:443
            timeout: 0s
      - config:
          '@type': type.googleapis.com/knoway.filters.v1alpha1.UsageStatsConfig
          statsServer:
            url: console.d.run:443
            timeout: 0s
      - config:
          '@type': type.googleapis.com/knoway.filters.v1alpha1.RateLimitConfig
          policies:
            - limit: 0
              baseOn: USER_ID
              duration: 30s
    accessLog:
      enable: true
  image:
    name: openai-image
    filters:
      - name: api-key-auth
        config:
          '@type': type.googleapis.com/knoway.filters.v1alpha1.APIKeyAuthConfig
          authServer:
            url: console.d.run:443
            timeout: 0s
      - config:
          '@type': type.googleapis.com/knoway.filters.v1alpha1.UsageStatsConfig
          statsServer:
            url: console.d.run:443
            timeout: 0s
      - config:
          '@type': type.googleapis.com/knoway.filters.v1alpha1.RateLimitConfig
          policies:
            - limit: 0
              based_on: USER_ID
              duration: 30s
    accessLog:
      enable: true
