debug: true
controller:
  probe_addr: ":8081"
  secure_metrics: false
  enable_http2: false

gateway:
  listener_addr: ":8080"
  auth_server:
    url: 10.33.2.23:31960
  stats_server:
    url: 10.33.2.23:31960
