debug: true
controller:
  secure_metrics: false
  enable_http2: false
kubeConfig: ""
gateway:
  auth_server:
    url: ''
    timeout: 0
  stats_server:
    url: ''
    timeout: 0
  log:
    access_log:
      enabled: true

  policy:
    rate_limit:
      enabled: true
