debug: true
controller:
  secure_metrics: false
  enable_http2: false
kubeConfig: ""
gateway:
  auth_server:
    url: ''
    timeout: 0
  stats_server:
    url: ''
    timeout: 0
  log:
    access_log:
      enabled: true

  policy:
    rate_limit:
      enabled: true
      # valid values: USER | API_KEY | API_KEY_AND_USER
      base_on: USER
      count: 50
      # Time window in seconds for rate limiting
      interval: 10