global:
  imageRegistry: release.daocloud.io
  # If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #  requests:
  #    cpu: 300m
  #    memory: 200Mi
  #  limits:
  #    cpu: 900m
  #    memory: 200Mi
  resources: {}
  imagePullPolicy: IfNotPresent
  # -- Global Docker registry secret names as an array
  imagePullSecrets: []
  high_available: false
  # Global node selector
  # If set, this will apply to all knoway components
  # Individual components can be set to a different node selector
  nodeSelector: {}
  # Global tolerations
  # If set, this will apply to all knoway components
  # Individual components can be set to a different tolerations
  tolerations: []
  # Global affinity
  # If set, this will apply to all knoway components
  # Individual components can be set to a different affinity
  affinity: {}

fullNameOverride: ""

debug: false
config:
  auth_server:
    url: ''
    # timeout in seconds, default is 3s
    timeout: 3
  stats_server:
    url: ''
    # timeout in seconds, default is 3s
    timeout: 3
  log:
    access_log:
      enabled: true
  policy:
    rate_limit:
      enabled: true

gateway:
  image:
    registry: ''
    repository: knoway/knoway-gateway
    tag:
  nodeSelector: {}
  tolerations: []
  affinity: {}
