// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using ListenerFilter within kubernetes types, where deepcopy-gen is used.
func (in *ListenerFilter) DeepCopyInto(out *ListenerFilter) {
	p := proto.Clone(in).(*ListenerFilter)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerFilter. Required by controller-gen.
func (in *ListenerFilter) DeepCopy() *ListenerFilter {
	if in == nil {
		return nil
	}
	out := new(ListenerFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListenerFilter. Required by controller-gen.
func (in *ListenerFilter) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ChatCompletionListener within kubernetes types, where deepcopy-gen is used.
func (in *ChatCompletionListener) DeepCopyInto(out *ChatCompletionListener) {
	p := proto.Clone(in).(*ChatCompletionListener)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChatCompletionListener. Required by controller-gen.
func (in *ChatCompletionListener) DeepCopy() *ChatCompletionListener {
	if in == nil {
		return nil
	}
	out := new(ChatCompletionListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ChatCompletionListener. Required by controller-gen.
func (in *ChatCompletionListener) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
